### ISSUE TITLE
关于群友操作会报错

### ISSUE THREAD

**Issue by huangyxHUTAO** [CCYellowStar2/zhenxun_plugin_slave_market#1]
尝试购买群友报错
![图片](https://github.com/CCYellowStar2/zhenxun_plugin_slave_market/assets/149290212/f9ba6147-c256-4308-8861-c803ab8f864d)
更新群友市场
![图片](https://github.com/CCYellowStar2/zhenxun_plugin_slave_market/assets/149290212/c6a3300d-2e78-4b17-8d11-8f30217d6ac4)

关于群友的所有操作都会报错（一键打工只有自己，所以没影响）
```
04-14 20:12:48 [SUCCESS] nonebot | OneBot V11 3778405902 | [message.group.normal]: Message -2147473126 from 3353255023@[群:909545776] '购买群友[at:qq=3500262572]'
04-14 20:12:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
04-14 20:12:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
04-14 20:12:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=basic_plugins.chat_history.chat_message)
04-14 20:12:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
04-14 20:12:48 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
04-14 20:12:48 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
04-14 20:12:48 [INFO] nonebot | Matcher(type='message', module=basic_plugins.chat_history.chat_message) running complete
04-14 20:12:48 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
04-14 20:12:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market)
04-14 20:12:48 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market) running complete
04-14 20:12:48 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market) failed.
Traceback (most recent call last):
  File "F:\zhenxun_bot-main(1)\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_slave_market\__init__.py", line 119, in _
    if user_ := await GroupInfoUser.get_or_none(user_qq=at[0], group_id=group_id):
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\queryset.py", line 1000, in __await__
    self._make_query()
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'user_qq'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_id', 'user_join_time', 'user_name']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\zhenxun_bot-main(1)\zhenxun_bot-main\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\huangyx\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\huangyx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\huangyx\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\huangyx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\huangyx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\huangyx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "F:\zhenxun_bot-main(1)\zhenxun_bot-main\extensive_plugin\zhenxun_plugin_slave_market\__init__.py", line 126, in _
    if user_ := await GroupInfoUser.get_or_none(user_qq=atqq, group_id=group_id):
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\queryset.py", line 1000, in __await__
    self._make_query()
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\queryset.py", line 962, in _make_query
    self.resolve_filters(
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\queryset.py", line 134, in resolve_filters
    modifier &= node.resolve(model, model._meta.basetable)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\expressions.py", line 359, in resolve
    return self._resolve_kwargs(model, table)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\expressions.py", line 317, in _resolve_kwargs
    key, value = self._get_actual_filter_params(model, raw_key, raw_value)
  File "C:\Users\huangyx\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-shKTsY7u-py3.9\lib\site-packages\tortoise\expressions.py", line 311, in _get_actual_filter_params
    raise FieldError(f"Unknown filter param '{key}'. Allowed base values are {allowed}")
tortoise.exceptions.FieldError: Unknown filter param 'user_qq'. Allowed base values are ['group_id', 'id', 'nickname', 'uid', 'user_id', 'user_join_time', 'user_name']
```

**Comment by CCYellowStar2** [comment]
我更新了那个__init__文件的代码，你把它复制覆盖过去

**Comment by Nenot233** [comment]
更新后指令：查看群友市场
报错
```
05-27 14:52:54 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.zhenxun_plugin_slave_market, lineno=54) failed.
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
 File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\zhenxun_plugin_slave_market\__init__.py", line 73, in _
    msg += f"|<img width='20%' src='http://q1.qlogo.cn/g?b=qq&nk={qq}&s=100'/>  {user_name}|{qq}|{p}|<img width='20%' src='http://q1.qlogo.cn/g?b=qq&nk={usern.user_qq}&s=100'/>  {umaster}|\n"
```
更新群友市场
```群友市场更新失败Multiple objects returned, expected exactly one```

破案了，是因为bot卡了导致两个人买了一个人，更新群友市场之后正常了，但是再次购买会复发
使用的是llone，猜测是无法读取群友列表导致的
